package chat.jaspr.gear;

import com.destroystokyo.paper.loottable.Lootable;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.UUID;
import org.bukkit.Bukkit;
import org.bukkit.GameMode;
import org.bukkit.Sound;
import org.bukkit.block.Block;
import org.bukkit.block.BlockState;
import org.bukkit.entity.Entity;
import org.bukkit.entity.HumanEntity;
import org.bukkit.entity.Player;
import org.bukkit.event.Event;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.inventory.ClickType;
import org.bukkit.event.inventory.InventoryAction;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.event.inventory.InventoryDragEvent;
import org.bukkit.event.inventory.InventoryType;
import org.bukkit.event.player.PlayerInteractEntityEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.event.world.WorldSaveEvent;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.PlayerInventory;

/**
 * 3.2.0 backpacks. Right-click a backpack in either hand, or right-click it (empty cursor) in your own
 * inventory screen, to open its chest-style window. Contents live in plugins/JasprGear/backpacks/UUID.pack
 * under the uuid stamped into the item on first open, never inside the item: moving, dropping or copying
 * the item can never duplicate what it holds, and two viewers of one backpack share one live inventory.
 * Backpacks never go inside backpacks. Saved on close, every 30 s while open and on every world save,
 * through GearStore's ordered atomic writer.
 *
 * Also the vanilla safety net: a chest or chest minecart that fills from a vanilla loot table (none are
 * generated by this world today) rolls GearApi.rollLoot once, like every structure chest.
 */
final class GearBackpacks implements Listener {
    static final String HEADER = "jaspr-pack 1";
    /** Loot tier used for vanilla loot-table containers (a modest vanilla dungeon). */
    static final int VANILLA_TIER = 1;
    private final GearPlugin plugin;
    final File dir;
    /** Live inventories by contents uuid; kept while viewed and for a while after, so a reopen never reads a stale file. */
    private final Map<UUID, Inventory> open = new HashMap<UUID, Inventory>();
    private final Map<UUID, String> saved = new HashMap<UUID, String>();
    private final Map<UUID, Long> idleSince = new HashMap<UUID, Long>();
    private final Map<UUID, Long> lastOpen = new HashMap<UUID, Long>();
    private final Random random = new Random();
    /** Loot-table containers with a roll already scheduled this tick (one click can fire more than one event). */
    private final java.util.Set<Object> pending = new java.util.HashSet<Object>();
    int opened, saves, refused, stamped, vanillaRolls, vanillaItems, corrupt;

    GearBackpacks(GearPlugin plugin) {
        this.plugin = plugin;
        this.dir = new File(plugin.getDataFolder(), "backpacks");
        plugin.getServer().getScheduler().runTaskTimer(plugin, () -> saveAll(false), 600L, 600L);
    }

    static final class PackHolder implements InventoryHolder {
        final UUID uuid;
        final GearBackpack pack;
        Inventory inventory;
        PackHolder(UUID uuid, GearBackpack pack) { this.uuid = uuid; this.pack = pack; }
        @Override public Inventory getInventory() { return inventory; }
    }

    static boolean isPack(Inventory inv) { return inv != null && inv.getHolder() instanceof PackHolder; }

    String metrics() {
        return "packsOpened=" + opened + " packSaves=" + saves + " packRefused=" + refused + " packsStamped=" + stamped
            + " packsLive=" + open.size() + " vanillaRolls=" + vanillaRolls + " vanillaItems=" + vanillaItems;
    }

    // ------------------------------------------------------------------ opening

    @EventHandler(priority = EventPriority.HIGH)
    public void onUse(PlayerInteractEvent e) {
        Action action = e.getAction();
        if (action != Action.RIGHT_CLICK_AIR && action != Action.RIGHT_CLICK_BLOCK) return;
        if (GearItems.backpack(e.getItem()) == null) return;
        e.setUseItemInHand(Event.Result.DENY); // a backpack is never a working hoe
        Player p = e.getPlayer();
        if (action == Action.RIGHT_CLICK_BLOCK && e.getClickedBlock() != null && !p.isSneaking()
            && GearPlugin.interactive(e.getClickedBlock().getType())) return; // doors and chests still open
        e.setCancelled(true);
        Long last = lastOpen.get(p.getUniqueId());
        long now = System.currentTimeMillis();
        if (last != null && now - last < 250) return; // one click fires for both hands
        lastOpen.put(p.getUniqueId(), now);
        boolean off = e.getHand() == EquipmentSlot.OFF_HAND;
        ItemStack held = off ? p.getInventory().getItemInOffHand() : p.getInventory().getItemInMainHand();
        ItemStack stamped = stamp(held);
        if (stamped == null) return;
        if (stamped != held) { if (off) p.getInventory().setItemInOffHand(stamped); else p.getInventory().setItemInMainHand(stamped); }
        open(p, stamped);
    }

    /** The stack with a contents uuid (the same object when it already has one), or null when no backpack. */
    ItemStack stamp(ItemStack stack) {
        if (GearItems.backpack(stack) == null || stack.getAmount() != 1) return null;
        if (GearItems.packUuid(stack) != null) return stack;
        stamped++;
        return GearItems.withPackUuid(stack, UUID.randomUUID());
    }

    /** Opens the backpack this (stamped) stack names. False when it cannot be opened. */
    boolean open(Player p, ItemStack stack) {
        GearBackpack pack = GearItems.backpack(stack);
        UUID uuid = GearItems.packUuid(stack);
        if (pack == null || uuid == null || !p.isOnline() || p.isDead() || !plugin.usable(p)) return false;
        Inventory inv = inventory(uuid, pack);
        if (inv == null) { p.sendMessage("§cThis backpack's contents could not be read; an admin can check the server log."); return false; }
        p.openInventory(inv);
        idleSince.remove(uuid);
        opened++;
        p.playSound(p.getLocation(), Sound.ITEM_ARMOR_EQUIP_LEATHER, 0.6f, 1.2f);
        return true;
    }

    /** The live inventory for a contents uuid, loaded from disk when needed; null when the file is unreadable and could not be moved aside. */
    Inventory inventory(UUID uuid, GearBackpack pack) {
        Inventory live = open.get(uuid);
        if (live != null) return live;
        ItemStack[] items;
        try {
            items = load(uuid);
        } catch (Exception bad) {
            File file = file(uuid), aside = new File(dir, uuid + ".pack.corrupt-" + System.currentTimeMillis());
            boolean moved = file.renameTo(aside);
            corrupt++;
            plugin.getLogger().warning("GEAR_PACK_LOAD_FAILED pack=" + uuid + " error=" + bad.getClass().getSimpleName()
                + " preserved=" + (moved ? aside.getName() : "in-place"));
            if (!moved) return null; // never overwrite a file we could not read
            items = new ItemStack[0];
        }
        int size = pack.slots();
        for (int i = items.length - 1; i >= size; i--) if (items[i] != null) { size = Math.min(54, (i / 9 + 1) * 9); break; }
        PackHolder holder = new PackHolder(uuid, pack);
        holder.inventory = Bukkit.createInventory(holder, size, "§" + pack.color() + pack.title);
        for (int i = 0; i < items.length && i < size; i++) holder.inventory.setItem(i, items[i]);
        open.put(uuid, holder.inventory);
        saved.put(uuid, encodeText(holder.inventory.getContents()));
        return holder.inventory;
    }

    File file(UUID uuid) { return new File(dir, uuid + ".pack"); }

    /** Slot contents from disk (an empty array when the backpack has never been saved). */
    ItemStack[] load(UUID uuid) throws Exception {
        File file = file(uuid);
        if (!file.isFile()) return new ItemStack[0];
        List<String> lines = Files.readAllLines(file.toPath(), StandardCharsets.UTF_8);
        if (lines.isEmpty() || !HEADER.equals(lines.get(0).trim())) throw new IOException("bad header");
        ItemStack[] items = new ItemStack[54];
        for (int n = 1; n < lines.size(); n++) {
            String line = lines.get(n).trim();
            if (line.isEmpty()) continue;
            int eq = line.indexOf('=');
            if (eq <= 0) throw new IOException("bad line");
            String key = line.substring(0, eq), value = line.substring(eq + 1);
            if (key.equals("id")) continue;
            int slot = Integer.parseInt(key);
            if (slot < 0 || slot >= items.length) throw new IOException("bad slot");
            items[slot] = GearItems.fromSnbt(new String(Base64.getDecoder().decode(value), StandardCharsets.UTF_8));
        }
        return items;
    }

    static String encodeText(ItemStack[] contents) {
        StringBuilder out = new StringBuilder(HEADER).append('\n');
        for (int i = 0; i < contents.length; i++) {
            if (GearItems.empty(contents[i])) continue;
            out.append(i).append('=').append(Base64.getEncoder().encodeToString(
                GearItems.toSnbt(contents[i]).getBytes(StandardCharsets.UTF_8))).append('\n');
        }
        return out.toString();
    }

    /** Writes this backpack when it changed since the last write (or always when forced). */
    void save(UUID uuid, boolean force) {
        Inventory inv = open.get(uuid);
        if (inv == null) return;
        String text = encodeText(inv.getContents());
        if (!force && text.equals(saved.get(uuid))) return;
        saved.put(uuid, text);
        plugin.store.writeAsync(dir, uuid + ".pack", text.getBytes(StandardCharsets.UTF_8));
        saves++;
    }

    /** Saves changed backpacks; drops cached ones nobody has viewed for five minutes. */
    void saveAll(boolean force) {
        long now = System.currentTimeMillis();
        for (Iterator<Map.Entry<UUID, Inventory>> it = open.entrySet().iterator(); it.hasNext(); ) {
            Map.Entry<UUID, Inventory> e = it.next();
            save(e.getKey(), force);
            if (!e.getValue().getViewers().isEmpty()) { idleSince.remove(e.getKey()); continue; }
            Long idle = idleSince.get(e.getKey());
            if (idle == null) idleSince.put(e.getKey(), now);
            else if (now - idle > 300_000L) { it.remove(); saved.remove(e.getKey()); idleSince.remove(e.getKey()); }
        }
    }

    /** Plugin shutdown: close every backpack window and queue the final writes (the caller flushes). */
    void closeAll() {
        for (Inventory inv : new ArrayList<Inventory>(open.values()))
            for (HumanEntity viewer : new ArrayList<HumanEntity>(inv.getViewers())) viewer.closeInventory();
        for (UUID uuid : new ArrayList<UUID>(open.keySet())) save(uuid, false);
    }

    @EventHandler(priority = EventPriority.MONITOR)
    public void onClose(InventoryCloseEvent e) {
        if (!isPack(e.getInventory())) return;
        PackHolder holder = (PackHolder) e.getInventory().getHolder();
        save(holder.uuid, false);
        if (e.getPlayer() instanceof Player) ((Player) e.getPlayer()).playSound(e.getPlayer().getLocation(), Sound.ITEM_ARMOR_EQUIP_LEATHER, 0.5f, 0.9f);
    }

    @EventHandler(priority = EventPriority.MONITOR)
    public void onWorldSave(WorldSaveEvent e) {
        if (e.getWorld() == Bukkit.getWorlds().get(0)) saveAll(false); // with the player data autosave
    }

    // ------------------------------------------------------------------ clicks

    @EventHandler(priority = EventPriority.LOW)
    public void onClick(InventoryClickEvent e) {
        if (!(e.getWhoClicked() instanceof Player)) return;
        final Player p = (Player) e.getWhoClicked();
        Inventory top = e.getView().getTopInventory();
        boolean packView = isPack(top);
        if (packView && movesPackIntoTop(e, top.getSize())) {
            e.setCancelled(true);
            refused++;
            p.sendMessage("§7Backpacks do not fit inside backpacks.");
            return;
        }
        // Right-click (empty cursor, not shift) on a backpack in your own inventory opens it.
        if (e.isCancelled() || e.getClick() != ClickType.RIGHT || !GearItems.empty(e.getCursor())) return;
        if (!(packView || e.getView().getType() == InventoryType.CRAFTING) || p.getGameMode() == GameMode.CREATIVE) return;
        if (!(e.getClickedInventory() instanceof PlayerInventory)) return;
        final ItemStack snapshot = e.getCurrentItem();
        if (GearItems.backpack(snapshot) == null || snapshot.getAmount() != 1) return;
        e.setCancelled(true);
        final int slot = e.getSlot();
        final ItemStack copy = snapshot.clone();
        plugin.getServer().getScheduler().runTask(plugin, () -> {
            if (!p.isOnline()) return;
            ItemStack now = p.getInventory().getItem(slot);
            if (now == null || !now.isSimilar(copy) || now.getAmount() != 1) { p.updateInventory(); return; }
            ItemStack stamped = stamp(now);
            if (stamped == null) return;
            if (stamped != now) p.getInventory().setItem(slot, stamped);
            p.closeInventory();
            open(p, stamped);
        });
    }

    /** True when this click would put a backpack into the backpack window above. */
    static boolean movesPackIntoTop(InventoryClickEvent e, int topSize) {
        int raw = e.getRawSlot();
        boolean inTop = raw >= 0 && raw < topSize;
        InventoryAction action = e.getAction();
        if (inTop) {
            if (GearItems.backpack(e.getCursor()) != null && (action == InventoryAction.PLACE_ALL || action == InventoryAction.PLACE_ONE
                || action == InventoryAction.PLACE_SOME || action == InventoryAction.SWAP_WITH_CURSOR)) return true;
            if (e.getClick() == ClickType.NUMBER_KEY) {
                ItemStack hot = e.getView().getBottomInventory().getItem(e.getHotbarButton());
                if (GearItems.backpack(hot) != null) return true;
            }
            return false;
        }
        return e.isShiftClick() && GearItems.backpack(e.getCurrentItem()) != null;
    }

    @EventHandler(priority = EventPriority.LOW)
    public void onDrag(InventoryDragEvent e) {
        Inventory top = e.getView().getTopInventory();
        if (!isPack(top) || GearItems.backpack(e.getOldCursor()) == null) return;
        for (int raw : e.getRawSlots()) if (raw < top.getSize()) { e.setCancelled(true); refused++; return; }
    }

    // ------------------------------------------------------------------ vanilla loot-table containers

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onLootBlock(PlayerInteractEvent e) {
        if (e.getAction() != Action.RIGHT_CLICK_BLOCK || e.getClickedBlock() == null || e.useInteractedBlock() == Event.Result.DENY) return;
        final Block block = e.getClickedBlock();
        BlockState state = block.getState();
        if (!(state instanceof Lootable) || !(state instanceof InventoryHolder) || !((Lootable) state).hasLootTable()) return;
        if (!pending.add(block.getLocation())) return;
        plugin.getServer().getScheduler().runTask(plugin, () -> {
            pending.remove(block.getLocation());
            BlockState now = block.getState();
            // Filled by vanilla (the loot table is consumed on fill): add one roll to the live inventory.
            if (now instanceof Lootable && now instanceof InventoryHolder && !((Lootable) now).hasLootTable())
                vanillaFill(((InventoryHolder) now).getInventory(), random);
        });
    }

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onLootEntity(PlayerInteractEntityEvent e) {
        final Entity entity = e.getRightClicked();
        if (!(entity instanceof Lootable) || !(entity instanceof InventoryHolder) || !((Lootable) entity).hasLootTable()) return;
        if (!pending.add(entity.getUniqueId())) return;
        plugin.getServer().getScheduler().runTask(plugin, () -> {
            pending.remove(entity.getUniqueId());
            if (entity.isValid() && !((Lootable) entity).hasLootTable()) vanillaFill(((InventoryHolder) entity).getInventory(), random);
        });
    }

    /** One GearApi roll into a random empty slot of a freshly filled vanilla container. */
    ItemStack vanillaFill(Inventory inv, Random r) {
        vanillaRolls++;
        ItemStack loot = GearApi.rollLoot(r, VANILLA_TIER);
        if (loot == null) return null;
        List<Integer> empty = new ArrayList<Integer>();
        ItemStack[] contents = inv.getContents();
        for (int i = 0; i < contents.length; i++) if (GearItems.empty(contents[i])) empty.add(i);
        if (empty.isEmpty()) return null;
        inv.setItem(empty.get(r.nextInt(empty.size())), loot); // live inventory: never BlockState.update() here
        vanillaItems++;
        plugin.getLogger().info("GEAR_VANILLA_LOOT item=" + describe(loot));
        return loot;
    }

    static String describe(ItemStack stack) {
        GearItem g = GearItems.identify(stack);
        if (g != null) return g.id;
        GearConsumable c = GearItems.consumable(stack);
        if (c != null) return c.id;
        GearBackpack b = GearItems.backpack(stack);
        return b != null ? b.id : String.valueOf(stack == null ? null : stack.getType());
    }

    /** Test hook: drops a backpack from the cache without saving it. */
    void forget(UUID uuid) { open.remove(uuid); saved.remove(uuid); idleSince.remove(uuid); }

    /** Test hook: every live backpack uuid (unmodifiable snapshot). */
    List<UUID> live() { return new ArrayList<UUID>(open.keySet()); }
}
