package chat.jaspr.biomes;

import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.bukkit.World;

/**
 * The 1.5x structure rate (3.25.0, owner request). Everything here is ADDITIVE: every site the 3.24 rules
 * place is still placed identically -- same anchor, same seed, same blocks -- and recognised exactly as
 * before. The extra sites come from
 *   - the catalogue: RELATIVE_STRUCTURE_DENSITY 0.20 -> 0.46 on the same fixed per-cell random. A cell below
 *     0.20 is "tier 0" and keeps the old rules verbatim; 0.20..0.46 is "tier 1" and yields to everything older
 *     (only ~38% of tier-1 cells can be built, hence 0.46 rather than 0.30 for 1.5x);
 *   - the set-piece register: a secondary lattice per structure with its own salt (Megaliths.C_CELL2, sized per
 *     structure so it adds half the primary count after its yields) that yields to every built primary, to
 *     higher-ranked secondaries, to older catalogue sites, older rooms and sanctuaries (Megaliths.secondaryFree);
 *   - the dungeon rooms: a third lattice for the eight doubled rooms, a second for the six single ones
 *     (Dungeons.D_CELL_C / D_SALT_C), sized the same way, yielding to everything older;
 *   - the vanilla-style rooms: 39 attempts per chunk instead of 26 (the first 26 draw exactly as before);
 *   - portal sanctuaries: at a seeded share of the square centres between the old ones (candidate()), yielding
 *     to older sites.
 * All sizes were measured with the rates probe (SA/work/r-rates: 96,000 x 96,000 blocks, 3.24.1 vs 3.25.0).
 * No secondary cell shares a factor above 2 with any room lattice: lattices whose spacings share a large
 * factor sit at one fixed offset from each other everywhere, and one of them then blocks the other.
 *
 * New sites also stay out of every chunk that existed when 3.25.0 first started (an immutable boundary, as
 * the expansion boundary does for the catalogue), so nothing is half built against old ground and the
 * dungeon retrofit never lays one into it. Precedence among new sites keeps the old order: set pieces, then
 * sanctuaries, then catalogue, then lattice rooms, then vanilla rooms; no test depends on a later one.
 */
public final class StructureRates {
    private StructureRates() {}

    /** What RELATIVE_STRUCTURE_DENSITY was before 3.25.0: a catalogue cell below it is tier 0 (old rules). */
    public static final double PREVIOUS_DENSITY = 0.20;
    public static final String BOUNDARY_FILE = "jaspr-rates-v1.boundary";
    private static final int BOUNDARY_MAGIC = 0x4a525231;
    /** Secondary set-piece lattices are sqrt 2 wider (half the sites) with a salt of their own. */
    static final double SECONDARY_SPACING = Math.sqrt(2.0);
    private static final long SECONDARY_SALT = 0x5345434F4E44L;       // "SECOND"

    static int secondaryCell(int cell) { return (int) Math.round(cell * SECONDARY_SPACING); }
    static long secondarySalt(long salt) { return salt * 31L + SECONDARY_SALT; }

    // == the upgrade boundary =======================================================================
    /** Seed -> boundary of the overworld generated by HorrorGenerator. A deny-all entry if it failed to open. */
    private static final Map<Long, WorldgenExpansion.Boundary> BOUNDARIES = new ConcurrentHashMap<>();
    private static final Map<Long, Boolean> FAILED = new ConcurrentHashMap<>();

    /** Opens (first start: snapshots) the boundary for the overworld. Called on WorldInitEvent, before any chunk. */
    public static synchronized int initialize(World world) {
        long seed = world.getSeed();
        WorldgenExpansion.Boundary known = BOUNDARIES.get(seed);
        if (known != null) return known.protectedChunks();
        try {
            WorldgenExpansion.Boundary b = WorldgenExpansion.open(world.getWorldFolder(), seed, BOUNDARY_FILE, BOUNDARY_MAGIC);
            BOUNDARIES.put(seed, b);
            FAILED.remove(seed);
            return b.protectedChunks();
        } catch (IOException | RuntimeException e) {
            // Fail closed: without the boundary no new site may be placed (old ones are unaffected).
            FAILED.put(seed, Boolean.TRUE);
            return -1;
        }
    }

    /** True when the rates boundary failed to open for this seed (new sites are then all refused). */
    public static boolean failed(long seed) { return FAILED.containsKey(seed); }

    /** True when no chunk of this box, nor the ring of chunks round it, existed before 3.25.0. */
    static boolean permits(long seed, int x, int z, int sizeX, int sizeZ) {
        if (FAILED.containsKey(seed)) return false;
        WorldgenExpansion.Boundary b = BOUNDARIES.get(seed);
        if (b == null || b.protectedChunks() == 0) return true;
        for (int cx = Math.floorDiv(x - 16, 16); cx <= Math.floorDiv(x + sizeX + 15, 16); cx++)
            for (int cz = Math.floorDiv(z - 16, 16); cz <= Math.floorDiv(z + sizeZ + 15, 16); cz++)
                if (b.contains(cx, cz)) return false;
        return true;
    }

    /** True when this chunk did not exist before 3.25.0 (the retrofit may lay only old work into old chunks). */
    static boolean fresh(long seed, int cx, int cz) {
        if (FAILED.containsKey(seed)) return false;
        WorldgenExpansion.Boundary b = BOUNDARIES.get(seed);
        return b == null || !b.contains(cx, cz);
    }

    // == portal sanctuaries ============================================================================
    /*
     * The original sanctuaries stand at chunk (8, 0) modulo 256 (HorrorGenerator.portalChunk, unchanged: the
     * importer and the catalogue's tier-0 reserve still ask exactly that). The new ones stand at the centres
     * of the squares between them -- as far from the old ones as the lattice allows -- on a seeded SELECT share
     * of those centres, and only where nothing older stands in the chunk itself (a sanctuary writes only its own
     * chunk). SELECT is set so that half as many again are built (rates probe, SA/work/r-rates).
     */
    static final int CENTRE_X = 136, CENTRE_Z = 128, SANCTUARY_HALO = 2;
    static final double SELECT = 0.56;

    /** A chunk the new sanctuary lattice could use (before admission). */
    static boolean candidate(long seed, int cx, int cz) {
        if (Math.floorMod(cx - CENTRE_X, 256) != 0 || Math.floorMod(cz - CENTRE_Z, 256) != 0) return false;
        long i = Math.floorDiv(cx - CENTRE_X, 256), j = Math.floorDiv(cz - CENTRE_Z, 256);
        return (Terrain.mix(seed + 0x53414E4354L + i * 341873128712L + j * 132897987541L) >>> 11) * 0x1.0p-53 < SELECT;
    }

    private static final Map<Long, Boolean> SANCTUARY_CACHE = new ConcurrentHashMap<>();

    /** True when a new (3.25.0) portal sanctuary stands in this chunk. */
    public static boolean sanctuary(Terrain t, int cx, int cz) {
        if (!candidate(t.seed, cx, cz)) return false;
        boolean ready = BOUNDARIES.containsKey(t.seed) || FAILED.containsKey(t.seed);
        long key = Terrain.mix(t.seed + cx * 341873128712L + cz * 132897987541L);
        Boolean known = ready ? SANCTUARY_CACHE.get(key) : null;
        if (known != null) return known;
        int x = cx * 16, z = cz * 16, size = 16;                      // its own chunk (each test adds a 2-block cordon)
        boolean ok = permits(t.seed, x, z, size, size)
            && !Megaliths.occupied(t, x, z, size, size, 255)            // a built (primary) set piece, any height
            && !StructurePlanner.catalogueTier0(t, x, z, size, size)   // an older catalogue site
            && !Dungeons.oldRoomNear(t, x, z, size, size);             // an older lattice room
        if (ready) { if (SANCTUARY_CACHE.size() > 4096) SANCTUARY_CACHE.clear(); SANCTUARY_CACHE.put(key, ok); }
        return ok;
    }

    /** True when this chunk is a sanctuary chunk or lies in the two-chunk halo of one (old or new). */
    static boolean nearSanctuary(Terrain t, int x, int z, int sizeX, int sizeZ) {
        int c0 = Math.floorDiv(x - 2, 16) - SANCTUARY_HALO, c1 = Math.floorDiv(x + sizeX + 1, 16) + SANCTUARY_HALO;
        int d0 = Math.floorDiv(z - 2, 16) - SANCTUARY_HALO, d1 = Math.floorDiv(z + sizeZ + 1, 16) + SANCTUARY_HALO;
        for (int cx = c0 + Math.floorMod(8 - c0, 256); cx <= c1; cx += 256)
            for (int cz = d0 + Math.floorMod(-d0, 256); cz <= d1; cz += 256)
                if (HorrorGenerator.portalChunk(cx, cz)) return true;
        for (int cx = c0 + Math.floorMod(CENTRE_X - c0, 256); cx <= c1; cx += 256)
            for (int cz = d0 + Math.floorMod(CENTRE_Z - d0, 256); cz <= d1; cz += 256)
                if (sanctuary(t, cx, cz)) return true;
        return false;
    }

    /** BiomeDetails keeps its motifs out of a new sanctuary's halo, as it does for the old ones. */
    static boolean newSanctuaryHalo(Terrain t, int cx, int cz) {
        for (int ax = cx - SANCTUARY_HALO; ax <= cx + SANCTUARY_HALO; ax++)
            for (int az = cz - SANCTUARY_HALO; az <= cz + SANCTUARY_HALO; az++)
                if (sanctuary(t, ax, az)) return true;
        return false;
    }

    /** The nearest standing sanctuary (old or new) to a block position, as {blockX, blockZ} of its centre. */
    public static int[] nearestSanctuary(Terrain t, int x, int z) {
        int bestX = (int) Math.round((x - 136) / 4096.0) * 4096 + 136, bestZ = (int) Math.round((z - 8) / 4096.0) * 4096 + 8;
        long best = sq(bestX - x, bestZ - z);
        int i0 = Math.floorDiv(Math.floorDiv(x, 16) - CENTRE_X, 256), j0 = Math.floorDiv(Math.floorDiv(z, 16) - CENTRE_Z, 256);
        for (int i = i0 - 1; i <= i0 + 2; i++) for (int j = j0 - 1; j <= j0 + 2; j++) {
            int cx = CENTRE_X + 256 * i, cz = CENTRE_Z + 256 * j;
            int bx = cx * 16 + 8, bz = cz * 16 + 8;
            long d = sq(bx - x, bz - z);
            if (d < best && sanctuary(t, cx, cz)) { best = d; bestX = bx; bestZ = bz; }
        }
        return new int[]{bestX, bestZ};
    }

    private static long sq(long a, long b) { return a * a + b * b; }

    /** For the server log (RATES_BOUNDARY_READY). */
    static File boundaryFile(World w) { return new File(w.getWorldFolder(), BOUNDARY_FILE); }
}
