'use strict';
// Regenerates client-mods/mobends/mobends-assets.js from the original Mo' Bends 1.2.2 resources (MIT):
// the wolf's .bendsanim keyframe files (base64, decoded at runtime by the core's BinaryAnimationLoader port)
// and textures/entity/wolf_misc.png as 64 ARGB ints (an 8x8 DynamicTexture for LayerWolfMisc).
// Usage: node scripts/mobends-assets.cjs [<MoBends source root>]
const fs = require('node:fs'), path = require('node:path'), zlib = require('node:zlib'), crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const source = process.argv[2] || 'C:/Users/AM/Downloads/MoBends-1.X-forge-1.12/MoBends-1.X-forge-1.12';
const assets = path.join(source, 'src/main/resources/assets/mobends');
// Only the animations wolf.json (the wolf's Kumo animator) refers to.
const ANIMATIONS = ['wolf_idle', 'wolf_walking', 'wolf_sitting_down', 'wolf_sitting', 'wolf_standing_up', 'wolf_breathing'];

function decodePng(file) {
  const b = fs.readFileSync(file);
  let o = 8, w = 0, h = 0, colorType = 0, depth = 0;
  const idat = [];
  while (o < b.length) {
    const len = b.readUInt32BE(o), type = b.toString('ascii', o + 4, o + 8), data = b.subarray(o + 8, o + 8 + len);
    if (type === 'IHDR') { w = data.readUInt32BE(0); h = data.readUInt32BE(4); depth = data[8]; colorType = data[9]; }
    if (type === 'IDAT') idat.push(data);
    o += 12 + len;
  }
  if (colorType !== 6 || depth !== 8) throw Error('expected 8-bit RGBA PNG');
  const raw = zlib.inflateSync(Buffer.concat(idat)), stride = w * 4, out = [];
  let prev = Buffer.alloc(stride);
  for (let y = 0; y < h; y++) {
    const filter = raw[y * (stride + 1)], line = Buffer.from(raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1)));
    for (let i = 0; i < stride; i++) {
      const a = i >= 4 ? line[i - 4] : 0, up = prev[i], c = i >= 4 ? prev[i - 4] : 0;
      let v = line[i];
      if (filter === 1) v += a; else if (filter === 2) v += up; else if (filter === 3) v += (a + up) >> 1;
      else if (filter === 4) { const p = a + up - c, pa = Math.abs(p - a), pb = Math.abs(p - up), pc = Math.abs(p - c); v += pa <= pb && pa <= pc ? a : pb <= pc ? up : c; }
      line[i] = v & 255;
    }
    for (let x = 0; x < w; x++) { const r = line[x * 4], g = line[x * 4 + 1], bl = line[x * 4 + 2], al = line[x * 4 + 3]; out.push(((al << 24) | (r << 16) | (g << 8) | bl) | 0); }
    prev = line;
  }
  return { w, h, pixels: out };
}

function build() {
  const animations = {};
  for (const name of ANIMATIONS) {
    const bytes = fs.readFileSync(path.join(assets, 'bends/animations', name + '.bendsanim'));
    animations['mobends:bends/animations/' + name + '.bendsanim'] = bytes.toString('base64');
  }
  const png = decodePng(path.join(assets, 'textures/entity/wolf_misc.png'));
  if (png.w !== 8 || png.h !== 8) throw Error('wolf_misc.png must be 8x8');
  const body = 'var JasprMoBendsAssets = ' + JSON.stringify({ animations, wolfMisc: png.pixels }) + ';\n';
  const sha = crypto.createHash('sha256').update(body).digest('hex');
  return '/* Mo\' Bends 1.2.2 resources (MIT, Copyright (c) 2017 Iwo Plaza): wolf keyframe animations and wolf_misc.png.\n' +
    ' * Generated by scripts/mobends-assets.cjs; do not edit. sha256 ' + sha + ' */\n' + body;
}
if (require.main === module) {
  const out = path.join(root, 'client-mods/mobends/mobends-assets.js');
  fs.writeFileSync(out, build());
  console.log('wrote ' + out + ' (' + fs.statSync(out).size + ' bytes)');
}
module.exports = { build, decodePng, ANIMATIONS };
